// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7I9XmF-WM-9qxwwx7O-3XjKoMqo8t8Fo',
    appId: '1:926775609416:web:c1696677c78c3e00f3b07d',
    messagingSenderId: '926775609416',
    projectId: 'critchat-906b4',
    authDomain: 'critchat-906b4.firebaseapp.com',
    databaseURL: 'https://critchat-906b4-default-rtdb.firebaseio.com',
    storageBucket: 'critchat-906b4.firebasestorage.app',
    measurementId: 'G-8PMBJCE96B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCExrzsBnJNQpEqZjpw942S60PnEjz46ng',
    appId: '1:926775609416:android:79eaa6efee5fc403f3b07d',
    messagingSenderId: '926775609416',
    projectId: 'critchat-906b4',
    databaseURL: 'https://critchat-906b4-default-rtdb.firebaseio.com',
    storageBucket: 'critchat-906b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2Z-oGidW7zkICI_NDUqOJurKSmyX6uUI',
    appId: '1:926775609416:ios:27c934f311335739f3b07d',
    messagingSenderId: '926775609416',
    projectId: 'critchat-906b4',
    databaseURL: 'https://critchat-906b4-default-rtdb.firebaseio.com',
    storageBucket: 'critchat-906b4.firebasestorage.app',
    iosClientId: '926775609416-udr4h2091shdbcaqr6j5nceg4aunft4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.critchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2Z-oGidW7zkICI_NDUqOJurKSmyX6uUI',
    appId: '1:926775609416:ios:27c934f311335739f3b07d',
    messagingSenderId: '926775609416',
    projectId: 'critchat-906b4',
    databaseURL: 'https://critchat-906b4-default-rtdb.firebaseio.com',
    storageBucket: 'critchat-906b4.firebasestorage.app',
    iosClientId: '926775609416-udr4h2091shdbcaqr6j5nceg4aunft4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.critchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7I9XmF-WM-9qxwwx7O-3XjKoMqo8t8Fo',
    appId: '1:926775609416:web:89532cab109ba66af3b07d',
    messagingSenderId: '926775609416',
    projectId: 'critchat-906b4',
    authDomain: 'critchat-906b4.firebaseapp.com',
    databaseURL: 'https://critchat-906b4-default-rtdb.firebaseio.com',
    storageBucket: 'critchat-906b4.firebasestorage.app',
    measurementId: 'G-LWZS08NNMK',
  );
}
