default_platform(:ios)

platform :ios do
  desc "Build and upload to Firebase App Distribution"
  lane :distribute do
    match(
      type: "appstore",
      readonly: true,
      git_url: ENV["MATCH_GIT_URL"],
      app_identifier: "net.lundandco.critchat"
    )
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store"
    )
    firebase_app_distribution(
      app: "1:926775609416:ios:27c934f311335739f3b07d",
      testers: "family-and-friends",
      service_credentials_file: ENV["FIREBASE_SERVICE_CREDENTIALS_FILE_PATH"]
    )
  end
end 