name: Build and Release Android App

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Decode Keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/critchat-keystore.jks

      - name: Verify Keystore Checksum
        run: shasum -a 256 android/critchat-keystore.jks

      - name: Create key.properties file
        run: |
          echo "storeFile=critchat-keystore.jks" > android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}" >> android/key.properties

      - name: Build Android App Bundle
        run: flutter build appbundle

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: 1:926775609416:android:79eaa6efee5fc403f3b07d
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CRITCHAT_906B4 }}
          file: build/app/outputs/bundle/release/app-release.aab
          groups: family-and-friends 