name: Build and Release iOS App

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Set up Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
          working-directory: 'ios'

      - name: Configure Git for private repo access
        run: git config --global url."https://x-access-token:${{ secrets.CERT_REPO_PAT }}@github.com/".insteadOf "https://github.com/"

      - name: Create Firebase Service Account file
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CRITCHAT_906B4 }}' > firebase_credentials.json

      - name: Create Fastlane .env file
        run: |
          echo "MATCH_PASSWORD=${{ secrets.MATCH_PASSWORD }}" > ios/fastlane/fastlane.env.default
          echo "FASTLANE_USER=${{ secrets.APPLE_DEVELOPER_EMAIL }}" >> ios/fastlane/fastlane.env.default
          echo "FASTLANE_PASSWORD=${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}" >> ios/fastlane/fastlane.env.default
          echo "FASTLANE_TEAM_ID=${{ secrets.APPLE_TEAM_ID }}" >> ios/fastlane/fastlane.env.default
          echo "MATCH_GIT_URL=${{ secrets.MATCH_GIT_URL }}" >> ios/fastlane/fastlane.env.default
          echo "FIREBASE_SERVICE_CREDENTIALS_FILE_PATH=${{ github.workspace }}/firebase_credentials.json" >> ios/fastlane/fastlane.env.default

      - name: Build and distribute
        run: |
          cd ios
          bundle exec fastlane distribute 